project:
  type: book
  output-dir: docs

book:
  title: "数据可视化探索(从入门到放弃)"
  author: "Multa-Head Wang Zhikun"
  date: "6/24/2025"

  cover-image: ./image/ggvis.png

  chapters:
    - index.qmd
    - quick_start.qmd

    - part: distribution.qmd
      chapters:
        - beeswarm.qmd
        - histogram.qmd
        - boxplot.qmd
        - density.qmd
        - ridgeline.qmd
        - violin.qmd

    - part: correlation.qmd
      chapters:
        - scatter.qmd
        - heatmap.qmd
        - correlogram.qmd
        - bubble.qmd
        - connected-scatter.qmd
        - density2d.qmd

    - part: ranking.qmd
      chapters:
        - bar.qmd
        - spider.qmd
        - wordcloud.qmd
        - parallel.qmd
        - lollipop.qmd
        - cir-bar.qmd
        - table.qmd

    - part: part-of-a-whole.qmd
      chapters:
        - group-bar.qmd
        - treemap.qmd
        - pie.qmd
        - donut.qmd
        - dendrogram.qmd
        - circular.qmd
        - waffle.qmd

    - part: evolution.qmd
      chapters:
        - line.qmd
        - area.qmd
        - stacked-area.qmd
        - stream.qmd
        - time.qmd

    - part: maps.qmd
      chapters:
        - map.qmd
        - choropleth.qmd
        - hexbin-map.qmd
        - cartogram.qmd
        - connection.qmd
        - bubble-map.qmd

    - part: flow.qmd
      chapters:
        - chord-diagram.qmd
        - network.qmd
        - sankey.qmd
        - arc-diagram.qmd
        - edge-bundling.qmd

    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-tools: true
    code-fold: true
    code-summary: "Show/Hide Code"
    number-sections: true

execute:
  warning: false
  cache: true
  freeze: auto
