project:
  type: book
  output-dir: docs

book:
  title: "数据可视化探索(从入门到放弃)"
  author: "Multa-Head Wang Zhikun"
  date: "6/24/2025"

  cover-image: ./image/ggvis.png

  chapters:
    - index.qmd
    - quick_start.qmd

    - part: distribution.qmd
      chapters:
        - beeswarm.qmd
        - histogram.qmd
        - boxplot.qmd
        - density.qmd
        - ridgeline.qmd
        - violin.qmd

    - part: correlation.qmd
      chapters:
        - scatter.qmd
        - heatmap.qmd
        - correlogram.qmd
        - bubble.qmd
        - connected-scatter.qmd
        - density2d.qmd

    # --part: Ranking



    - part: part-of-a-whole.qmd
      chapters:
        - bar.qmd
        - treemap.qmd
        - donut.qmd
        - pie.qmd
        - dendrogram.qmd
        - circular.qmd
        - waffle.qmd


    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-tools: true
    code-fold: true
    code-summary: "Show/Hide Code"
    number-sections: true
  pdf:
    documentclass: scrreprt

execute:
  warning: false
  cache: true
  freeze: auto
